window.CHALLENGE_CARDS_BY_LANG = window.CHALLENGE_CARDS_BY_LANG || {};
window.CHALLENGE_CARDS_BY_LANG.en = [
  { name: 'European collector', text: 'Collect 1 team from each of the 5 major leagues: Premier League, La Liga, Serie A, Bundesliga and Ligue 1.' },
  { name: 'English treble', text: 'Control 3 territories in the same round using different Premier League teams.' },
  { name: 'La Liga at home', text: 'Conquer Spain with a La Liga team and keep control for 3 turns.' },
  { name: 'Protected Italy', text: 'Conquer Italy with a Serie A team and keep control for 3 turns.' },
  { name: 'German wall', text: 'Conquer Germany with a Bundesliga team and keep control for 3 turns.' },
  { name: 'Continental blue', text: 'Conquer France with a Ligue 1 team and keep control for 3 turns.' },
  { name: 'Iberian dominance', text: 'Control 3 territories in Europe in the same round using different teams from Portugal or Spain.' },
  { name: 'Superclasico', text: 'Collect River Plate and Boca Juniors in the same match.' },
  { name: 'Strong Argentina', text: 'Control 3 territories in South America using Liga Argentina teams.' },
  { name: 'Global MLS', text: 'Conquer 3 territories in the same round using different MLS teams.' },
  { name: 'Total Dutch football', text: 'Control 3 territories in the same round using different Eredivisie teams.' },
  { name: 'Dutch quartet', text: 'Collect 3 from Ajax, PSV, Feyenoord and AZ Alkmaar.' },
  { name: 'Saudi power', text: 'Dominate Israel with a Saudi team using the swap power and keep control for 3 rounds.' },
  { name: 'Turkish treble', text: 'Control 3 territories in the same round using different Super Lig teams.' },
  { name: 'Vikings', text: 'Conquer 3 territories in the same round using different teams from Norway, Sweden or Denmark.' },
  { name: 'Eastern Europe', text: 'Control 3 territories in the same round using different teams from Poland, Romania or Hungary.' },
  { name: 'Scotland resists', text: 'Control 3 territories in the same round using different teams from Scotland.' },
  { name: 'Low altitude', text: 'Control 3 territories in the same round using different teams from Belgium, Netherlands or Switzerland.' },
  { name: 'Atlantic bridge', text: 'Conquer 4 territories by sea attack in the same round.' },
  { name: 'Unbreakable base', text: 'Defend your base successfully without losing any team 3 times.' },
  { name: 'Continental comeback', text: 'Conquer territories on 4 different continents in the same round.' },
  { name: 'European siege', text: 'Control 6 territories in Europe at the same time.' },
  { name: 'African expansion', text: 'Control 5 territories in Africa at the same time.' },
  { name: 'World Cup', text: 'Control Brazil, Germany, Italy, Argentina and France at the same time.' },
  { name: 'BRICS', text: 'Control Brazil, Russia, China, India and South Africa at the same time.' },
  { name: 'Iberian empire', text: 'Control Spain, Portugal, Brazil, Argentina and Mexico at the same time.' },
  { name: 'Mediterranean route', text: 'Control Spain, France, Italy, Greece and Turkey at the same time.' },
  { name: 'Pacific powers', text: 'Control United States, Japan, South Korea, Australia and Mexico at the same time.' },
  { name: 'Heart of Europe', text: 'Control Germany, France, Italy, Switzerland and Austria at the same time.' },
  { name: 'Complete America', text: 'Control Canada, United States, Mexico, Brazil and Argentina at the same time.' },
  { name: 'African Cup', text: 'Control Egypt, Nigeria, Cameroon, Senegal and Morocco at the same time.' },
  { name: 'Gold Coast', text: 'Control Senegal, Ivory Coast, Ghana, Nigeria and Cameroon at the same time.' },
  { name: 'Asian Tigers', text: 'Control Japan, South Korea, China, India and Australia at the same time.' },
  { name: 'Silk Road', text: 'Control Turkey, Iran, Saudi Arabia, India and China at the same time.' }
];
