window.CHALLENGE_CARDS_BY_LANG = window.CHALLENGE_CARDS_BY_LANG || {};
window.CHALLENGE_CARDS_BY_LANG.es = [
  { name: 'Coleccionista europeo', text: 'Consigue 1 equipo de cada una de las 5 grandes ligas: Premier League, La Liga, Serie A, Bundesliga y Ligue 1.' },
  { name: 'Triplete ingles', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de la Premier League.' },
  { name: 'La Liga en casa', text: 'Conquista Espana con un equipo de La Liga y manten el control por 3 turnos.' },
  { name: 'Italia protegida', text: 'Conquista Italia con un equipo de Serie A y manten el control por 3 turnos.' },
  { name: 'Muralla alemana', text: 'Conquista Alemania con un equipo de Bundesliga y manten el control por 3 turnos.' },
  { name: 'Azul continental', text: 'Conquista Francia con un equipo de Ligue 1 y manten el control por 3 turnos.' },
  { name: 'Dominio iberico', text: 'Controla 3 territorios en Europa en la misma ronda usando diferentes equipos de Portugal o Espana.' },
  { name: 'Superclasico', text: 'Consigue River Plate y Boca Juniors en la misma partida.' },
  { name: 'Argentina fuerte', text: 'Controla 3 territorios de Sudamerica usando equipos de la Liga Argentina.' },
  { name: 'MLS global', text: 'Conquista 3 territorios en la misma ronda usando diferentes equipos de la MLS.' },
  { name: 'Holanda total', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de la Eredivisie.' },
  { name: 'Cuarteto holandes', text: 'Consigue 3 entre Ajax, PSV, Feyenoord y AZ Alkmaar.' },
  { name: 'Poder saudita', text: 'Domina Israel con un equipo saudita usando el poder de intercambio y manten el control por 3 rondas.' },
  { name: 'Triplete turco', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de la Super Lig.' },
  { name: 'Vikingos', text: 'Conquista 3 territorios en la misma ronda usando diferentes equipos de Noruega, Suecia o Dinamarca.' },
  { name: 'Europa del Este', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de Polonia, Rumania o Hungria.' },
  { name: 'Escocia resiste', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de Escocia.' },
  { name: 'Baja altitud', text: 'Controla 3 territorios en la misma ronda usando diferentes equipos de Belgica, Holanda o Suiza.' },
  { name: 'Puente atlantico', text: 'Conquista 4 territorios por ataque maritimo en la misma ronda.' },
  { name: 'Base inviolable', text: 'Defiende tu base con exito sin perder ningun equipo 3 veces.' },
  { name: 'Remontada continental', text: 'Conquista territorios en 4 continentes diferentes en la misma ronda.' },
  { name: 'Asedio europeo', text: 'Controla 6 territorios en Europa al mismo tiempo.' },
  { name: 'Expansion africana', text: 'Controla 5 territorios en Africa al mismo tiempo.' },
  { name: 'Copa del Mundo', text: 'Controla Brasil, Alemania, Italia, Argentina y Francia al mismo tiempo.' },
  { name: 'BRICS', text: 'Controla Brasil, Rusia, China, India y Sudafrica al mismo tiempo.' },
  { name: 'Imperio iberico', text: 'Controla Espana, Portugal, Brasil, Argentina y Mexico al mismo tiempo.' },
  { name: 'Ruta del Mediterraneo', text: 'Controla Espana, Francia, Italia, Grecia y Turquia al mismo tiempo.' },
  { name: 'Potencias del Pacifico', text: 'Controla Estados Unidos, Japon, Corea del Sur, Australia y Mexico al mismo tiempo.' },
  { name: 'Corazon de Europa', text: 'Controla Alemania, Francia, Italia, Suiza y Austria al mismo tiempo.' },
  { name: 'America completa', text: 'Controla Canada, Estados Unidos, Mexico, Brasil y Argentina al mismo tiempo.' },
  { name: 'Copa Africana', text: 'Controla Egipto, Nigeria, Camerun, Senegal y Marruecos al mismo tiempo.' },
  { name: 'Costa de Oro', text: 'Controla Senegal, Costa de Marfil, Ghana, Nigeria y Camerun al mismo tiempo.' },
  { name: 'Tigres asiaticos', text: 'Controla Japon, Corea del Sur, China, India y Australia al mismo tiempo.' },
  { name: 'Ruta de la Seda', text: 'Controla Turquia, Iran, Arabia Saudita, India y China al mismo tiempo.' }
];
