window.CHALLENGE_CARDS_BY_LANG = window.CHALLENGE_CARDS_BY_LANG || {};
window.CHALLENGE_CARDS_BY_LANG.fr = [
  { name: 'Collectionneur europeen', text: 'Recupere 1 equipe de chacun des 5 grands championnats: Premier League, La Liga, Serie A, Bundesliga et Ligue 1.' },
  { name: 'Triple anglais', text: 'Controle 3 territoires dans le meme round avec differentes equipes de Premier League.' },
  { name: 'La Liga a domicile', text: 'Conquiers l Espagne avec une equipe de La Liga et garde le controle pendant 3 tours.' },
  { name: 'Italie protegee', text: 'Conquiers l Italie avec une equipe de Serie A et garde le controle pendant 3 tours.' },
  { name: 'Mur allemand', text: 'Conquiers l Allemagne avec une equipe de Bundesliga et garde le controle pendant 3 tours.' },
  { name: 'Bleu continental', text: 'Conquiers la France avec une equipe de Ligue 1 et garde le controle pendant 3 tours.' },
  { name: 'Domination iberique', text: 'Controle 3 territoires en Europe dans le meme round avec differentes equipes du Portugal ou d Espagne.' },
  { name: 'Superclassico', text: 'Recupere River Plate et Boca Juniors dans la meme partie.' },
  { name: 'Argentine forte', text: 'Controle 3 territoires en Amerique du Sud avec des equipes de Liga Argentina.' },
  { name: 'MLS globale', text: 'Conquiers 3 territoires dans le meme round avec differentes equipes de MLS.' },
  { name: 'Pays-Bas total', text: 'Controle 3 territoires dans le meme round avec differentes equipes d Eredivisie.' },
  { name: 'Quatuor neerlandais', text: 'Recupere 3 parmi Ajax, PSV, Feyenoord et AZ Alkmaar.' },
  { name: 'Puissance saoudienne', text: 'Domine Israel avec une equipe saoudienne en utilisant le pouvoir d echange et garde le controle pendant 3 rounds.' },
  { name: 'Triple turc', text: 'Controle 3 territoires dans le meme round avec differentes equipes de Super Lig.' },
  { name: 'Vikings', text: 'Conquiers 3 territoires dans le meme round avec differentes equipes de Norvege, Suede ou Danemark.' },
  { name: 'Europe de l Est', text: 'Controle 3 territoires dans le meme round avec differentes equipes de Pologne, Roumanie ou Hongrie.' },
  { name: 'L Ecosse resiste', text: 'Controle 3 territoires dans le meme round avec differentes equipes d Ecosse.' },
  { name: 'Basse altitude', text: 'Controle 3 territoires dans le meme round avec differentes equipes de Belgique, des Pays-Bas ou de Suisse.' },
  { name: 'Pont atlantique', text: 'Conquiers 4 territoires par attaque maritime dans le meme round.' },
  { name: 'Base inviolable', text: 'Defends ta base avec succes sans perdre aucune equipe 3 fois.' },
  { name: 'Retour continental', text: 'Conquiers des territoires sur 4 continents differents dans le meme round.' },
  { name: 'Siege europeen', text: 'Controle 6 territoires en Europe en meme temps.' },
  { name: 'Expansion africaine', text: 'Controle 5 territoires en Afrique en meme temps.' },
  { name: 'Coupe du Monde', text: 'Controle le Bresil, l Allemagne, l Italie, l Argentine et la France en meme temps.' },
  { name: 'BRICS', text: 'Controle le Bresil, la Russie, la Chine, l Inde et l Afrique du Sud en meme temps.' },
  { name: 'Empire iberique', text: 'Controle l Espagne, le Portugal, le Bresil, l Argentine et le Mexique en meme temps.' },
  { name: 'Route mediterraneenne', text: 'Controle l Espagne, la France, l Italie, la Grece et la Turquie en meme temps.' },
  { name: 'Puissances du Pacifique', text: 'Controle les Etats-Unis, le Japon, la Coree du Sud, l Australie et le Mexique en meme temps.' },
  { name: 'Coeur de l Europe', text: 'Controle l Allemagne, la France, l Italie, la Suisse et l Autriche en meme temps.' },
  { name: 'Amerique complete', text: 'Controle le Canada, les Etats-Unis, le Mexique, le Bresil et l Argentine en meme temps.' },
  { name: 'Coupe Africaine', text: 'Controle l Egypte, le Nigeria, le Cameroun, le Senegal et le Maroc en meme temps.' },
  { name: 'Cote de l Or', text: 'Controle le Senegal, la Cote d Ivoire, le Ghana, le Nigeria et le Cameroun en meme temps.' },
  { name: 'Tigres asiatiques', text: 'Controle le Japon, la Coree du Sud, la Chine, l Inde et l Australie en meme temps.' },
  { name: 'Route de la Soie', text: 'Controle la Turquie, l Iran, l Arabie Saoudite, l Inde et la Chine en meme temps.' }
];
