window.CHALLENGE_CARDS_BY_LANG = window.CHALLENGE_CARDS_BY_LANG || {};
window.CHALLENGE_CARDS_BY_LANG.it = [
  { name: 'Collezionista europeo', text: 'Raccogli 1 squadra da ciascuno dei 5 grandi campionati: Premier League, La Liga, Serie A, Bundesliga e Ligue 1.' },
  { name: 'Tripletta inglese', text: 'Controlla 3 territori nello stesso round usando diverse squadre della Premier League.' },
  { name: 'La Liga in casa', text: 'Conquista la Spagna con una squadra de La Liga e mantieni il controllo per 3 turni.' },
  { name: 'Italia protetta', text: 'Conquista l Italia con una squadra di Serie A e mantieni il controllo per 3 turni.' },
  { name: 'Muro tedesco', text: 'Conquista la Germania con una squadra di Bundesliga e mantieni il controllo per 3 turni.' },
  { name: 'Blu continentale', text: 'Conquista la Francia con una squadra di Ligue 1 e mantieni il controllo per 3 turni.' },
  { name: 'Dominio iberico', text: 'Controlla 3 territori in Europa nello stesso round usando diverse squadre di Portogallo o Spagna.' },
  { name: 'Superclassico', text: 'Raccogli River Plate e Boca Juniors nella stessa partita.' },
  { name: 'Argentina forte', text: 'Controlla 3 territori in Sud America usando squadre della Liga Argentina.' },
  { name: 'MLS globale', text: 'Conquista 3 territori nello stesso round usando diverse squadre della MLS.' },
  { name: 'Olanda totale', text: 'Controlla 3 territori nello stesso round usando diverse squadre della Eredivisie.' },
  { name: 'Quartetto olandese', text: 'Raccogli 3 tra Ajax, PSV, Feyenoord e AZ Alkmaar.' },
  { name: 'Potere saudita', text: 'Domina Israele con una squadra saudita usando il potere di scambio e mantieni il controllo per 3 round.' },
  { name: 'Tripletta turca', text: 'Controlla 3 territori nello stesso round usando diverse squadre della Super Lig.' },
  { name: 'Vichinghi', text: 'Conquista 3 territori nello stesso round usando diverse squadre di Norvegia, Svezia o Danimarca.' },
  { name: 'Europa dell Est', text: 'Controlla 3 territori nello stesso round usando diverse squadre di Polonia, Romania o Ungheria.' },
  { name: 'La Scozia resiste', text: 'Controlla 3 territori nello stesso round usando diverse squadre della Scozia.' },
  { name: 'Bassa quota', text: 'Controlla 3 territori nello stesso round usando diverse squadre di Belgio, Olanda o Svizzera.' },
  { name: 'Ponte atlantico', text: 'Conquista 4 territori tramite attacco marittimo nello stesso round.' },
  { name: 'Base inviolabile', text: 'Difendi la tua base con successo senza perdere nessuna squadra per 3 volte.' },
  { name: 'Rimonta continentale', text: 'Conquista territori in 4 continenti diversi nello stesso round.' },
  { name: 'Assedio europeo', text: 'Controlla 6 territori in Europa contemporaneamente.' },
  { name: 'Espansione africana', text: 'Controlla 5 territori in Africa contemporaneamente.' },
  { name: 'Coppa del Mondo', text: 'Controlla Brasile, Germania, Italia, Argentina e Francia contemporaneamente.' },
  { name: 'BRICS', text: 'Controlla Brasile, Russia, Cina, India e Sudafrica contemporaneamente.' },
  { name: 'Impero iberico', text: 'Controlla Spagna, Portogallo, Brasile, Argentina e Messico contemporaneamente.' },
  { name: 'Rotta del Mediterraneo', text: 'Controlla Spagna, Francia, Italia, Grecia e Turchia contemporaneamente.' },
  { name: 'Potenze del Pacifico', text: 'Controlla Stati Uniti, Giappone, Corea del Sud, Australia e Messico contemporaneamente.' },
  { name: 'Cuore d Europa', text: 'Controlla Germania, Francia, Italia, Svizzera e Austria contemporaneamente.' },
  { name: 'America completa', text: 'Controlla Canada, Stati Uniti, Messico, Brasile e Argentina contemporaneamente.' },
  { name: 'Coppa Africana', text: 'Controlla Egitto, Nigeria, Camerun, Senegal e Marocco contemporaneamente.' },
  { name: 'Costa d Oro', text: 'Controlla Senegal, Costa d Avorio, Ghana, Nigeria e Camerun contemporaneamente.' },
  { name: 'Tigri asiatiche', text: 'Controlla Giappone, Corea del Sud, Cina, India e Australia contemporaneamente.' },
  { name: 'Via della Seta', text: 'Controlla Turchia, Iran, Arabia Saudita, India e Cina contemporaneamente.' }
];
